Repository tylerturdenpants/ember-attacher, pull requests merged in 2021-05, with the labels that each got.

#479 Remove addons that use old AST builder syntax API's
  package.json
  tests/dummy/app/styles/app.scss
  tests/dummy/app/templates/application.hbs
  tests/dummy/app/templates/components/attachment-example.hbs
  yarn.lock
Labels: bug, internal

#427 update to ember-qunit 5
  package.json
  tests/index.html
  tests/test-helper.js
  yarn.lock
Labels: enhancement, internal

#488 Remove excess whitespace content
  addon/templates/components/attach-popover.hbs
  tests/integration/components/ember-attacher/ember-attacher-test.js
Labels: enhancement
